
//CODE_ROLE
const CODE_ROLE_SUDO='SUDO'
const CODE_ROLE_ADMIN='ADMIN'
//CODE_LOCAL_STORAGE
const CODE_LS_LANG='LANG'
const CODE_LS_USER='USER'
const CODE_LS_TOKEN='TOKEN'
const CODE_LS_MENU='MENU'
//HEADER G-PARAMETERS CODE
const CODE_LOCATION='LOCL'
const CODE_DOCUMET_TYPE='TDOC'
const CODE_STATUS_ACCOUNT='ESTDCTA'
const CODE_STATUS_READING='ESTDRDG'
const CODE_MONTH='MONTH'
const CODE_YEAR='YEAR'

//G-PARAMETERS-DETAILS CODE
const CODE_FINAL_CONSUMER='TDOCCF'
const CODE_DNI='TDOCCE'
const CODE_PASSPORT='TDOCPS'
const CODE_RUC='TDOCRC'
const CODE_EXT='TDOCXT'
//MONTH code start in 0
//YEAR code is year same

const CODE_STATUS_ACCOUNT_DELETE='0'
const CODE_STATUS_ACCOUNT_ACTIVE='1'
const CODE_STATUS_ACCOUNT_SUSPENDED='5'

const CODE_STATUS_CUSTOMER_DELETE=false
const CODE_STATUS_CUSTOMER_ACTIVE=true

const CODE_STATUS_READING_DELETE='0'
const CODE_STATUS_READING_ACTIVE='1'
const CODE_STATUS_READING_PAID='2'
const CODE_STATUS_READING_RESUIDE='3'


export {CODE_LOCATION,CODE_DOCUMET_TYPE,CODE_STATUS_ACCOUNT,
    CODE_FINAL_CONSUMER,CODE_DNI,CODE_PASSPORT,CODE_RUC,CODE_EXT,CODE_STATUS_ACCOUNT_DELETE,CODE_STATUS_ACCOUNT_ACTIVE,
    CODE_STATUS_ACCOUNT_SUSPENDED,CODE_STATUS_CUSTOMER_ACTIVE,CODE_ROLE_SUDO,CODE_ROLE_ADMIN,CODE_LS_LANG,CODE_LS_USER,
    CODE_LS_TOKEN,CODE_LS_MENU,CODE_MONTH,CODE_YEAR,CODE_STATUS_READING,CODE_STATUS_READING_ACTIVE,CODE_STATUS_READING_RESUIDE
}